title: "Luna Yue Huang"
meta_author: "Luna Yue Huang"
short_description: "Economist / Data Scientist"
meta_description: "Economist / Data Scientist"
meta_keywords: "economics, data science, UC Berkeley, Waymo"

profile_pic: "/assets/img/profile.png"
cv_short_file: "/assets/pdf/cv_short.pdf"
github: "https://github.com/luna983"
linkedin: "https://www.linkedin.com/in/luna983"
gscholar: "https://scholar.google.com/citations?hl=en&user=wLG71k4AAAAJ"

google_analytics: "UA-115019672-1"
