title: "Luna Yue Huang"
meta_author: "Luna Yue Huang"
short_description: "Economist + Data Scientist"
long_description: "Ph.D. Candidate at UC Berkeley<br>Part-time Data Scientist at Google X<br>On the 2021 Job Market"
meta_description: "Ph.D. Candidate at UC Berkeley | Part-time Data Scientist at Google X | On the 2021 Job Market"
meta_keywords: "economics, data science, UC Berkeley"

profile_pic: "/assets/img/profile.png"
cv_short_file: "/assets/pdf/cv_short.pdf"
github: "https://github.com/luna983"
linkedin: "https://www.linkedin.com/in/luna983"
gscholar: "https://scholar.google.com/citations?hl=en&user=wLG71k4AAAAJ"

google_analytics: "UA-115019672-1"
