title: "Luna Yue Huang"
meta_author: "Luna Yue Huang"
short_description: "Economist + Data Scientist"
long_description: "Ph.D. Candidate at UC Berkeley<br>AI Resident at Google X<br>On the 2021 Job Market"
meta_description: "Ph.D. Candidate at UC Berkeley | AI Resident at Google X | On the 2021 Job Market"
meta_keywords: "economics, data science, UC Berkeley"

profile_pic: "/assets/img/profile.png"
cv_long_file: "/assets/pdf/cv_long.pdf"
cv_short_file: "/assets/pdf/cv_short.pdf"
email: "yuehuang@berkeley.edu"
github: "https://github.com/luna983"
linkedin: "https://www.linkedin.com/in/luna983"
gscholar: "https://scholar.google.com/citations?hl=en&user=wLG71k4AAAAJ"

url: "luna-yue-huang.com"
long_url: "http://luna-yue-huang.com"

google_analytics: "UA-115019672-1"
