title: "Luna Yue Huang"
short_description: "Development Economist"
long_description: "Ph.D. Student at UC Berkeley"
meta_description: "Ph.D. Student in development economics at UC Berkeley"
meta_keywords: "development economics, urban economics, economics, UC Berkeley"
meta_author: "Luna Yue Huang"

profile_pic: "/assets/img/profile.jpg"
profile_credit: "Max Chiyu Jiang"
profile_link: "http://www.maxjiang.ml"
cv_file: "/assets/pdf/cv.pdf"
email: "yuehuang@berkeley.edu"
github: "https://github.com/luna983"

url: "luna-yue-huang.com"
long_url: "http://luna-yue-huang.com"

google_analytics: "UA-115019672-1"
